### ISSUE TITLE
errors running deploy.sh

### ISSUE THREAD

**Issue by revodavid** [sethjuarez/vision#7]
```
david@Azure:~/vision$ sh deploy.sh confboost

...

No functions version specified so defaulting to 2. In the future, specifying a version will be required. To create a 2.x function you would pass in the flag `--functions-version 2`
Your Linux function app 'confboostfuncapp', that uses a consumption plan has been successfully created but is not active until content is published using Azure Portal or the Functions Core Tools.
Application Insights "confboostfuncapp" was created for this Function App. You can visit 

...

Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip._internal.cli.main import main
ImportError: No module named 'pip._internal.cli'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'azure.cognitiveservices'
No connection string, account key or sas token found, we will query account keys for your storage account. Please try to use --auth-mode login or provide one of the following parameters: connection string, account key or sas token for your storage account.

...

Changing "confboostappcred" to a valid URI of "http://confboostappcred", which is the required format used for service principal names
Found an existing application instance of "REDACTED". We will patch it
Creating a role assignment under the scope of "/subscriptions/REDACTED/resourceGroups/confboost"
GitHub Secrets
```

**Comment by revodavid** [comment]
This error was traced to `pip` not working in my instance of the Azure Cloud Shell. It was resolved by [Resetting my cloud shell settings](https://docs.microsoft.com/en-us/azure/cloud-shell/troubleshooting#delete).

**Comment by sethjuarez** [comment]
Awesome - sorry for the HUUUGE delay. Closing
